name: amankrmj_portfolio
description: "My Portfolio Website using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #*Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0


  #*Architecture
  flutter_hooks: ^0.21.2
  url_strategy: ^0.3.0

  #*Services
  url_launcher: ^6.3.1
  http: ^1.4.0

  #*Services
  collapsible_sidebar: ^2.0.7
  animated_text_kit: ^4.2.3
  simple_animations: ^5.2.0
  oktoast: ^3.4.0
  animations: ^2.0.11
  get: ^4.7.2
  visibility_detector: ^0.4.0+2
  rive: ^0.13.20
  flutter_svg: ^2.1.0
  responsive_layout_builder: ^0.5.0
  flutter_staggered_grid_view: ^0.7.0
  pdf_image_renderer: ^1.0.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  window_manager: ^0.5.0
  atlas_icons: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
    - assets/icons/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900

    - family: ShantellSans
      fonts:
        - asset: assets/fonts/shantell_sans/ShantellSans-Regular.ttf
        - asset: assets/fonts/shantell_sans/ShantellSans-Italic.ttf
          style: italic
        - asset: assets/fonts/shantell_sans/ShantellSans-Light.ttf
          weight: 100
        - asset: assets/fonts/shantell_sans/ShantellSans-Light.ttf
          weight: 200
        - asset: assets/fonts/shantell_sans/ShantellSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/shantell_sans/ShantellSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/shantell_sans/ShantellSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/shantell_sans/ShantellSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/shantell_sans/ShantellSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/shantell_sans/ShantellSans-ExtraBold.ttf
          weight: 900
