name: amankrmj_portfolio
description: "My Portfolio Website using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #*Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0


  #*Architecture
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  responsive_builder: ^0.7.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_hooks: ^0.21.2
  url_strategy: ^0.3.0

  #*Services
  url_launcher: ^6.3.1
  http: ^1.4.0

  #*Services
  collapsible_sidebar: ^2.0.7
  animated_text_kit: ^4.2.3
  simple_animations: ^5.2.0
  oktoast: ^3.4.0
  flutter_neumorphic: ^3.2.0
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf