name: portfolio
description: "My Portfolio Website using Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #*Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0


  #*Architecture
  flutter_hooks: ^0.21.2
  url_strategy: ^0.3.0

  #*Services
  url_launcher: ^6.3.2
  http: ^1.4.0

  #*Services
  collapsible_sidebar: ^2.0.7
  animated_text_kit: ^4.2.3
  simple_animations: ^5.2.0
  animations: ^2.0.11
  get: ^4.7.2
  rive: ^0.13.20
  flutter_svg: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  window_manager: ^0.5.1
  atlas_icons: ^0.0.12
  pretty_animated_text: ^2.0.0
  velocity_x: ^4.3.1
  timelines_plus: ^1.0.7
  mesh_gradient: ^1.3.8
  aura_box: ^1.0.2
  crypto: ^3.0.6
  intl: ^0.20.2
  logger: ^2.6.0
  animated_containers: ^1.1.0

  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
    - assets/icons/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
    - family: ShantellSans
      fonts:
        - asset: assets/fonts/shantell_sans/ShantellSans-Regular.ttf
        - asset: assets/fonts/shantell_sans/ShantellSans-Bold.ttf
        - asset: assets/fonts/shantell_sans/ShantellSans-Italic.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans/NotoSans-Regular.ttf
        - asset: assets/fonts/notosans/NotoSans-Bold.ttf
        - asset: assets/fonts/notosans/NotoSans-Italic.ttf
        - asset: assets/fonts/notosans/NotoSans-BoldItalic.ttf
