import 'package:portfolio/domain/models/tools_model/tools.model.dart';

import '../domain/models/about_me_info_model/about.me.info.model.dart';

final aboutMeInfo = AboutMeInfoModel(
  name: "Aman Kumar",
  profession: "Aspiring Software Engineer",
  location: "Sonebhadra, Uttar Pradesh, India",
  interests: ["Coding", "Music", "Traveling"],
  experience: "2 years",
  education: "B.Tech in Electronics and Computer Engineering",
  email: "amankr@gmail.com",
  summary: "Based in Varanasi,",
  technicalInterests: [
    "Flutter",
    "Dart",
    "Firebase",
    "REST APIs",
    "Machine Learning",
    "UI/UX Design",
    "Open Source",
    "Cloud Computing",
    "DevOps",
  ],
);

final List<ToolsModel> tools = [
  ToolsModel(
    name: "Css",
    image: "svg_icons/css.svg",
    url: "https://www.w3.org/Style/CSS/Overview.en.html",
    color: "0xFF1172b8",
    width: 60,
  ),
  ToolsModel(
    name: "Javascript",
    image: "svg_icons/javascript.svg",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    color: "0xFFF7DF1E",
    width: 170,
  ),
  ToolsModel(
    name: "Java",
    image: "svg_icons/java.svg",
    url: "https://www.java.com",
    color: "0xFF007396",
    width: 70,
  ),
  ToolsModel(
    name: "Kotlin",
    image: "svg_icons/kotlin.svg",
    url: "https://kotlinlang.org",
    color: "0xFF7F52FF",
    width: 100,
  ),
  ToolsModel(
    name: "Python",
    image: "svg_icons/python.svg",
    url: "https://www.python.org",
    color: "0xFF3776AB",
    width: 110,
  ),
  ToolsModel(
    name: "Html",
    image: "svg_icons/html.svg",
    url: "https://html.spec.whatwg.org",
    color: "0xFFf16529",
    width: 60,
  ),
  ToolsModel(
    name: "Django",
    image: "svg_icons/django.svg",
    url: "https://www.djangoproject.com",
    color: "0xFF44b78b",
    width: 80,
  ),
  ToolsModel(
    name: "Flutter",
    image: "svg_icons/flutter.svg",
    url: "https://flutter.dev",
    color: "0xFF41d0fd",
    width: 90,
  ),
  ToolsModel(
    name: "Spring",
    image: "svg_icons/spring.svg",
    url: "https://spring.io",
    color: "0xFF6DB33F",
    width: 70,
  ),
  ToolsModel(
    name: "Mongodb",
    image: "svg_icons/mongodb.svg",
    url: "https://www.mongodb.com",
    color: "0xFF47A248",
    width: 90,
  ),
  ToolsModel(
    name: "Pgsql",
    image: "svg_icons/pgsql.svg",
    url: "https://www.postgresql.org",
    color: "0xFF336791",
    width: 70,
  ),
  ToolsModel(
    name: "Gitlab",
    image: "svg_icons/gitlab.svg",
    url: "https://gitlab.com",
    color: "0xFFfc6d26",
    width: 80,
  ),
  ToolsModel(
    name: "Git",
    image: "svg_icons/git.svg",
    url: "https://git-scm.com",
    color: "0xFFee513b",
    width: 50,
  ),
  ToolsModel(
    name: "Github",
    image: "svg_icons/github.svg",
    url: "https://github.com",
    color: "0xFF3e75c3",
    width: 70,
  ),
  ToolsModel(
    name: "Docker",
    image: "svg_icons/docker.svg",
    url: "https://www.docker.com",
    color: "0xFF1794d4",
    width: 70,
  ),
  ToolsModel(
    name: "Android Studio",
    image: "svg_icons/android_studio.svg",
    url: "https://developer.android.com/studio",
    color: "0xFF45d286",
    width: 130,
  ),
  ToolsModel(
    name: "Intellij Idea",
    image: "svg_icons/intellij_idea.svg",
    url: "https://www.jetbrains.com/idea/",
    color: "0xFFab47bc",
    width: 100,
  ),
  ToolsModel(
    name: "Spring Boot",
    image: "svg_icons/spring_boot.svg",
    url: "https://spring.io/projects/spring-boot",
    color: "0xFF6DB33F",
    width: 90,
  ),
  ToolsModel(
    name: "Postman",
    image: "svg_icons/postman.svg",
    url: "https://www.postman.com",
    color: "0xFF7B7B7B",
    width: 70,
  ),
  ToolsModel(
    name: "Pycharm",
    image: "svg_icons/pycharm.svg",
    url: "https://www.jetbrains.com/pycharm/",
    color: "0xFFc9eb61",
    width: 70,
  ),
  ToolsModel(
    name: "VS Code",
    image: "svg_icons/vscode.svg",
    url: "https://code.visualstudio.com",
    color: "0xFF1f9cf0",
    width: 70,
  ),
  ToolsModel(
    name: "Figma",
    image: "svg_icons/figma.svg",
    url: "https://figma.com",
    color: "0xFFa259ff",
    width: 70,
  ),
  ToolsModel(
    name: "Canva",
    image: "svg_icons/canva.svg",
    url: "https://canva.com",
    color: "0xFF248fda",
    width: 70,
  ),
];
