// import '../domain/models/about.me.info.model.dart';
//
// final AboutMeInfoModel aboutMe = AboutMeInfoModel(
//   name: 'Aman Kumar',
//   profession: 'Aspiring Software Engineer',
//   location: 'New Delhi, India',
//   interests: ['Coding', 'Music', 'Traveling'],
//   experience: '3 years',
//   education: 'B.Tech in Computer Science',
//   email: 'aman.kumar@email.com',
//   summary:
//       'Based in Varanasi, I completed my high school education locally and earned a B.Tech in Electronics and Computer Engineering from VIT Chennai in 2026. I am passionate about full stack Java development and have hands-on experience building applications and websites using Java and Flutter. During my academic journey, I actively participated in numerous cultural and technical events, and also served as the head of the organizing committee for a technical club in college.',
//   technicalInterests: [
//     'Flutter',
//     'Dart',
//     'Firebase',
//     'REST APIs',
//     'Machine Learning',
//     'UI/UX Design',
//     'Open Source',
//     'Cloud Computing',
//     'DevOps',
//   ],
//   tools: [
//     ToolModel(
//       name: "Css",
//       image: "svg_icons/css-3-svgrepo-com.svg",
//       url: "https://www.w3.org/Style/CSS/Overview.en.html",
//       color: 0xFF1172b8,
//       width: 60,
//     ),
//     ToolModel(
//       name: "Javascript",
//       image: "svg_icons/javascript-svgrepo-com.svg",
//       url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
//       color: 0xFFF7DF1E,
//       width: 170,
//     ),
//     ToolModel(
//       name: "Java",
//       image: "svg_icons/java-svgrepo-com.svg",
//       url: "https://www.java.com",
//       color: 0xFF007396,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Kotlin",
//       image: "svg_icons/kotlin-svgrepo-com.svg",
//       url: "https://kotlinlang.org",
//       color: 0xFF7F52FF,
//       width: 100,
//     ),
//     ToolModel(
//       name: "Python",
//       image: "svg_icons/python-svgrepo-com.svg",
//       url: "https://www.python.org",
//       color: 0xFF3776AB,
//       width: 110,
//     ),
//     ToolModel(
//       name: "Html",
//       image: "svg_icons/html-5-svgrepo-com.svg",
//       url: "https://html.spec.whatwg.org",
//       color: 0xFFf16529,
//       width: 60,
//     ),
//     ToolModel(
//       name: "Django",
//       image: "svg_icons/django-svgrepo-com.svg",
//       url: "https://www.djangoproject.com",
//       color: 0xFF44b78b,
//       width: 80,
//     ),
//     ToolModel(
//       name: "Flutter",
//       image: "svg_icons/flutter-svgrepo-com.svg",
//       url: "https://flutter.dev",
//       color: 0xFF41d0fd,
//       width: 90,
//     ),
//     ToolModel(
//       name: "Spring",
//       image: "svg_icons/spring-svgrepo-com.svg",
//       url: "https://spring.io",
//       color: 0xFF6DB33F,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Mongodb",
//       image: "svg_icons/mongodb-svgrepo-com.svg",
//       url: "https://www.mongodb.com",
//       color: 0xFF47A248,
//       width: 90,
//     ),
//     ToolModel(
//       name: "Pgsql",
//       image: "svg_icons/pgsql-svgrepo-com.svg",
//       url: "https://www.postgresql.org",
//       color: 0xFF336791,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Gitlab",
//       image: "svg_icons/gitlab-svgrepo-com.svg",
//       url: "https://gitlab.com",
//       color: 0xFFfc6d26,
//       width: 80,
//     ),
//     ToolModel(
//       name: "Git",
//       image: "svg_icons/git-svgrepo-com.svg",
//       url: "https://git-scm.com",
//       color: 0xFFee513b,
//       width: 50,
//     ),
//     ToolModel(
//       name: "Github",
//       image: "svg_icons/github-color-svgrepo-com.svg",
//       url: "https://github.com",
//       color: 0xFF3e75c3,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Docker",
//       image: "svg_icons/docker-svgrepo-com.svg",
//       url: "https://www.docker.com",
//       color: 0xFF1794d4,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Android Studio",
//       image: "svg_icons/icons8-android-studio.svg",
//       url: "https://developer.android.com/studio",
//       color: 0xFF45d286,
//       width: 130,
//     ),
//     ToolModel(
//       name: "Intellij Idea",
//       image: "svg_icons/icons8-intellij-idea.svg",
//       url: "https://www.jetbrains.com/idea/",
//       color: 0xFFab47bc,
//       width: 100,
//     ),
//     ToolModel(
//       name: "Spring Boot",
//       image: "svg_icons/icons8-spring-boot.svg",
//       url: "https://spring.io/projects/spring-boot",
//       color: 0xFF6DB33F,
//       width: 90,
//     ),
//     ToolModel(
//       name: "Postman",
//       image: "svg_icons/postman-icon-svgrepo-com.svg",
//       url: "https://www.postman.com",
//       color: 0xFF7B7B7B,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Pycharm",
//       image: "svg_icons/pycharm-svgrepo-com.svg",
//       url: "https://www.jetbrains.com/pycharm/",
//       color: 0xFFc9eb61,
//       width: 70,
//     ),
//     ToolModel(
//       name: "Vscode",
//       image: "svg_icons/vscode-svgrepo-com.svg",
//       url: "https://code.visualstudio.com",
//       color: 0xFF1f9cf0,
//       width: 70,
//     ),
//   ],
// );
