name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - gh-pages
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Clean old build (optional)
        run: rm -rf ./build/web

      - name: Build Flutter Web using Wasm
        run: flutter build web --wasm

      - name: Move files to root for GitHub Pages
        run: |
          mkdir gh-pages-deploy
          cp -r build/web/* gh-pages-deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-deploy
          force_orphan: true