name: Deploy Flutter Web to GitHub Pages

on:
  push:
    tags:
      - '*'   # Triggers on any tag push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Show Flutter version and location
        run: |
          which flutter
          flutter --version
          echo $PATH

      - name: Force Flutter tool upgrade & precache web
        run: |
          flutter upgrade --force
          flutter doctor
          flutter precache --web

      - name: Clean old build
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web using CanvasKit
        run: flutter build web --release --web-renderer canvaskit --base-href=/amankrmj_portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true