name: Deploy Flutter Web (WASM) to GitHub Pages

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      - name: Clean old builds
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web (WASM)
        run: flutter build web --wasm --release --base-href=/portfolio/ \
          --dart-define=ABSTRACT_EMAIL=${{ secrets.ABSTRACT_EMAIL }} \
          --dart-define=ABSTRACT_PHONE=${{ secrets.ABSTRACT_PHONE }} \
          --dart-define=PORTFOLIO_READ_WRITE=${{ secrets.PORTFOLIO_READ_WRITE }}


      #      - name: Unpublish previous GitHub Pages content
      #        run: |
      #          git fetch origin gh-pages:gh-pages || echo 'No gh-pages branch yet.'
      #          git checkout gh-pages || git checkout --orphan gh-pages
      #          git rm -rf . || echo 'Nothing to remove.'
      #          git commit -am "chore: clear previous GitHub Pages content" || echo 'Nothing to commit.'
      #          git push origin gh-pages --force
      #          git checkout -

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build/web
          force_orphan: true