name: Deploy Flutter Web to GitHub Pages

on:
  push:
    tags:
      - '*'   # Triggers on any tag push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Show Flutter version and location
        run: |
          which flutter
          flutter --version
          echo $PATH

      - name: Remove system Flutter (if present)
        run: |
          sudo rm -rf /opt/hostedtoolcache/flutter
          sudo rm -rf /usr/local/bin/flutter
        continue-on-error: true

      - name: Clean old build
        run: $FLUTTER_HOME/bin/flutter clean

      - name: Install dependencies
        run: $FLUTTER_HOME/bin/flutter pub get

      - name: Build Flutter Web using CanvasKit
        run: $FLUTTER_HOME/bin/flutter build web --release --web-renderer canvaskit --base-href=/amankrmj_portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true